#!/usr/bin/env node
/**
 * contracts-sync.mjs — push contracts/ into the native repos (copy + generate). One source of truth, two apps.
 *
 * Usage:
 *   node tools/contracts-sync.mjs            # write into ios/ and android/
 *   node tools/contracts-sync.mjs --check    # CI: exit 1 if any repo copy is missing, stale or hand-edited
 *   node tools/contracts-sync.mjs --only strings,analytics,copy   [--platform ios|android] [--allow-missing]
 *
 * Driven by contracts/sync.config.json (see contracts/README.md):
 *   copy       files/dirs copied verbatim (OpenAPI documents, JSON fixtures)
 *   strings    contracts/strings/<locale>.json (i18next-style, nested or flat)
 *              → iOS Localizable.xcstrings (+ optional typed L10n accessors, + optional InfoPlist.xcstrings for
 *                Info.plist keys such as CFBundleDisplayName), Android res/values[-xx]/strings.xml
 *              {{name}} → %1$@ / %1$s ({{count}} → %lld / %d); key_one/key_other (and legacy key/key_plural) → plurals
 *   analytics  contracts/analytics/events.json → Swift enum AnalyticsEvent / Kotlin sealed interface AnalyticsEvent
 * Design tokens are generated with Style Dictionary (see guidelines/08-shared-contracts.md), not by this tool.
 *
 * Each repo gets a manifest (.contracts-sync.json) listing what was generated, so files that are no longer
 * produced (a removed fixture or locale) are deleted on sync and reported by --check. --check also fails when a
 * configured repo is missing (use --allow-missing to skip it). .xcstrings files are compared as JSON, because
 * Xcode may reformat them.
 */
import fs from 'node:fs';
import path from 'node:path';
import { WORKSPACE, parseArgs, printHelp, walk } from './lib/common.mjs';

const args = parseArgs(process.argv.slice(2), ['help', 'check', 'allow-missing']);
if (args.help) { printHelp(import.meta.url); process.exit(0); }
const root = path.resolve(args.workspace ?? WORKSPACE);
const configPath = path.join(root, 'contracts', 'sync.config.json');
if (!fs.existsSync(configPath)) { console.error('✖ contracts/sync.config.json not found'); process.exit(1); }
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
const only = args.only ? new Set(String(args.only).split(',')) : null;
const want = (k) => !only || only.has(k);
const GEN = 'GENERATED by tools/contracts-sync.mjs from contracts/ — DO NOT EDIT';
const MANIFEST = '.contracts-sync.json';

/** @type {Map<string, string|Buffer>} absolute path -> expected content */
const outputs = new Map();
const warnings = [];
const repos = [];
const missingRepos = [];
let stale = 0;
const sameJson = (a, b) => { try { return stableJson(JSON.parse(a.toString())) === stableJson(JSON.parse(String(b))); } catch { return false; } };
function stableJson(v) {
  if (Array.isArray(v)) return `[${v.map(stableJson).join(',')}]`;
  if (v && typeof v === 'object') return `{${Object.keys(v).sort().map((k) => `${JSON.stringify(k)}:${stableJson(v[k])}`).join(',')}}`;
  return JSON.stringify(v);
}

// ---------- copy ----------
function planCopy(from, to) {
  if (!fs.existsSync(from)) { warnings.push(`copy source ${path.relative(root, from)} not found`); return; }
  if (fs.statSync(from).isFile()) { outputs.set(to, fs.readFileSync(from)); return; }
  for (const f of walk(from)) if (!path.basename(f).startsWith('.')) outputs.set(path.join(to, path.relative(from, f)), fs.readFileSync(f));
}

// ---------- strings ----------
function loadStrings() {
  const sc = config.strings ?? {};
  const dir = path.resolve(root, sc.sourceDir ?? 'contracts/strings');
  if (!fs.existsSync(dir)) return null;
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));
  if (!files.length) return null;
  const base = sc.baseLocale ?? 'en';
  const locales = {};
  for (const f of files) locales[path.basename(f, '.json')] = flatten(JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')));
  if (!locales[base]) { warnings.push(`strings: base locale file ${base}.json missing`); return null; }
  const PLURAL = /_(zero|one|two|few|many|other)$/;
  const entries = new Map(); // key -> { plural: bool, placeholders: [names] }
  const baseFlat = locales[base];
  for (const k of Object.keys(baseFlat)) {
    const pm = k.match(PLURAL);
    if (pm) { const key = k.slice(0, -pm[0].length); entries.set(key, { plural: true, placeholders: placeholders(baseFlat[k], entries.get(key)?.placeholders) }); continue; }
    if (k.endsWith('_plural')) continue; // legacy i18next v3 plural, handled with its singular below
    entries.set(k, { plural: `${k}_plural` in baseFlat, placeholders: placeholders(baseFlat[k] + (baseFlat[`${k}_plural`] ?? '')) });
    if (/\$t\(/.test(baseFlat[k])) warnings.push(`strings: "${k}" uses $t() nesting, which is not supported natively; inline it`);
  }
  const value = (loc, key, form) => {
    const flat = locales[loc];
    if (!form) return flat[key];
    if (form in LEGACY && `${key}_${form}` in flat === false) return form === 'one' ? flat[key] : flat[`${key}_plural`];
    return flat[`${key}_${form}`];
  };
  for (const [loc, flat] of Object.entries(locales)) {
    if (loc === base) continue;
    for (const k of Object.keys(flat)) {
      const bk = k.replace(PLURAL, '').replace(/_plural$/, '');
      if (!entries.has(bk)) warnings.push(`strings: ${loc}.json has "${k}" which is not in ${base}.json (ignored)`);
    }
  }
  return { base, locales: Object.keys(locales).sort((a, b) => (a === base ? -1 : b === base ? 1 : a.localeCompare(b))), entries, value };
}
const LEGACY = { one: 1, other: 1 };
const FORMS = ['zero', 'one', 'two', 'few', 'many', 'other'];

function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, key, out); else out[key] = String(v);
  }
  return out;
}
function placeholders(text, existing = []) {
  const names = [...existing];
  for (const m of String(text).matchAll(/\{\{\s*([\w.]+)[^}]*\}\}/g)) if (!names.includes(m[1])) names.push(m[1]);
  return names;
}
function convert(text, names, platform) {
  if (text == null) return null;
  const hasPh = /\{\{/.test(text);
  let s = hasPh ? text.replace(/%/g, '%%') : text;
  s = s.replace(/\{\{\s*([\w.]+)[^}]*\}\}/g, (_, n) => {
    const i = names.indexOf(n) + 1;
    const int = n === 'count';
    return platform === 'ios' ? `%${i}$${int ? 'lld' : '@'}` : `%${i}$${int ? 'd' : 's'}`;
  });
  return s;
}
function genXcstrings(src) {
  const strings = {};
  for (const [key, e] of [...src.entries].sort(([a], [b]) => a.localeCompare(b))) {
    const localizations = {};
    for (const loc of src.locales) {
      if (!e.plural) {
        const v = convert(src.value(loc, key), e.placeholders, 'ios');
        if (v != null) localizations[loc] = { stringUnit: { state: 'translated', value: v } };
        continue;
      }
      const plural = {};
      for (const form of FORMS) {
        const v = convert(src.value(loc, key, form), e.placeholders, 'ios');
        if (v != null) plural[form] = { stringUnit: { state: 'translated', value: v } };
      }
      if (Object.keys(plural).length) localizations[loc] = { variations: { plural } };
    }
    strings[key] = { comment: GEN, extractionState: 'manual', localizations };
  }
  return JSON.stringify({ sourceLanguage: src.base, strings, version: '1.0' }, null, 2) + '\n';
}
function androidName(key) {
  let n = key.replace(/[^A-Za-z0-9_]/g, '_');
  if (!/^[A-Za-z_]/.test(n)) n = `_${n}`;
  return n;
}
function androidValuesDir(loc, base) {
  if (loc === base) return 'values';
  const parts = loc.split(/[-_]/);
  if (parts.length === 1) return `values-${parts[0]}`;
  if (parts.length === 2 && /^[A-Z]{2}$|^\d{3}$/.test(parts[1])) return `values-${parts[0]}-r${parts[1]}`;
  return `values-b+${parts.join('+')}`;
}
function xmlEscape(s) {
  let v = s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/'/g, "\\'").replace(/\n/g, '\\n');
  if (/^[@?]/.test(v)) v = `\\${v}`;
  return v;
}
function genAndroidStrings(src) {
  const seen = new Map();
  for (const key of src.entries.keys()) {
    const n = androidName(key);
    if (seen.has(n)) warnings.push(`strings: "${key}" and "${seen.get(n)}" both map to Android name ${n}`);
    seen.set(n, key);
  }
  const files = [];
  for (const loc of src.locales) {
    const lines = [`<?xml version="1.0" encoding="utf-8"?>`, `<!-- ${GEN} -->`, `<resources>`];
    for (const [key, e] of [...src.entries].sort(([a], [b]) => a.localeCompare(b))) {
      const name = androidName(key);
      if (!e.plural) {
        const v = convert(src.value(loc, key), e.placeholders, 'android');
        if (v != null) lines.push(`    <string name="${name}"${!e.placeholders.length && v.includes('%') ? ' formatted="false"' : ''}>${xmlEscape(v)}</string>`);
        continue;
      }
      const items = FORMS.map((f) => [f, convert(src.value(loc, key, f), e.placeholders, 'android')]).filter(([, v]) => v != null);
      if (!items.length) continue;
      if (items.some(([f]) => f === 'zero') && loc.startsWith('en')) warnings.push(`strings: "${key}_zero" is ignored by Android for English (quantity="zero" only applies to languages with a zero category)`);
      lines.push(`    <plurals name="${name}">`, ...items.map(([f, v]) => `        <item quantity="${f}">${xmlEscape(v)}</item>`), `    </plurals>`);
    }
    lines.push(`</resources>`, '');
    files.push([androidValuesDir(loc, src.base), lines.join('\n')]);
  }
  return files;
}

/** InfoPlist.xcstrings: localizes Info.plist keys (e.g. CFBundleDisplayName) from contract strings (e.g. app.name). */
function genInfoPlistStrings(src, mapping) {
  const strings = {};
  for (const [contractKey, plistKey] of Object.entries(mapping).sort(([, a], [, b]) => a.localeCompare(b))) {
    const e = src.entries.get(contractKey);
    if (!e) { warnings.push(`strings: infoPlist maps "${contractKey}" → ${plistKey}, but contracts/strings has no "${contractKey}"`); continue; }
    if (e.plural || e.placeholders.length) { warnings.push(`strings: "${contractKey}" can't be an Info.plist value (plural or placeholders)`); continue; }
    const localizations = {};
    for (const loc of src.locales) {
      const v = src.value(loc, contractKey);
      if (v != null) localizations[loc] = { stringUnit: { state: 'translated', value: v } };
    }
    strings[plistKey] = { comment: `${GEN} (from ${contractKey})`, extractionState: 'manual', localizations };
  }
  return JSON.stringify({ sourceLanguage: src.base, strings, version: '1.0' }, null, 2) + '\n';
}

function genSwiftAccessors(src, bundleExpr) {
  const ident = (k) => { let id = camel(k); if (/^\d/.test(id)) id = `_${id}`; return SWIFT_KW.has(id) ? `\`${id}\`` : id; };
  const used = new Map();
  const L = [`// ${GEN}`, '// Typed accessors for contracts/strings. Use these instead of String(localized:) with interpolation,', '// which would look up a different key (e.g. "auth.login.greeting %@").', 'import Foundation', '', 'public enum L10n {'];
  for (const [key, e] of [...src.entries].sort(([a], [b]) => a.localeCompare(b))) {
    let name = ident(key);
    if (used.has(name)) { warnings.push(`strings: "${key}" and "${used.get(name)}" both map to Swift accessor ${name}; using ${name}_2`); name = `${name}_2`; }
    used.set(name, key);
    const baseText = src.value(src.base, key, e.plural ? 'other' : null) ?? '';
    L.push(`    /// ${e.plural ? 'plural · ' : ''}${JSON.stringify(baseText).slice(1, -1)}`);
    if (!e.placeholders.length) { L.push(`    public static var ${name}: String { tr("${key}") }`); continue; }
    const params = e.placeholders.map((p) => `${ident(p).replace(/`/g, '')}: ${p === 'count' ? 'Int' : 'String'}`).join(', ');
    L.push(`    public static func ${name}(${params}) -> String { tr("${key}", ${e.placeholders.map((p) => ident(p)).join(', ')}) }`);
  }
  L.push('}', '', 'private func tr(_ key: String, _ args: any CVarArg...) -> String {',
    `    let format = ${bundleExpr}.localizedString(forKey: key, value: nil, table: "Localizable")`,
    '    return args.isEmpty ? format : String(format: format, locale: Locale.current, arguments: args)', '}');
  return L.join('\n') + '\n';
}

// ---------- analytics ----------
function loadEvents() {
  const file = path.resolve(root, config.analytics?.source ?? 'contracts/analytics/events.json');
  if (!fs.existsSync(file)) return null;
  const list = JSON.parse(fs.readFileSync(file, 'utf8')).events ?? [];
  const names = new Set();
  for (const e of list) {
    if (!e.name) throw new Error('analytics: event without "name"');
    if (names.has(e.name)) throw new Error(`analytics: duplicate event "${e.name}"`);
    names.add(e.name);
  }
  return [...list].sort((a, b) => a.name.localeCompare(b.name));
}
const camel = (s) => s.replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : '')).replace(/^[A-Z]/, (c) => c.toLowerCase());
const pascal = (s) => camel(s).replace(/^[a-z]/, (c) => c.toUpperCase());
const SWIFT_KW = new Set(['associatedtype', 'class', 'deinit', 'enum', 'extension', 'func', 'import', 'init', 'inout', 'internal', 'let', 'operator', 'private', 'protocol', 'public', 'static', 'struct', 'subscript', 'typealias', 'var', 'break', 'case', 'continue', 'default', 'defer', 'do', 'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return', 'switch', 'where', 'while', 'as', 'catch', 'false', 'is', 'nil', 'rethrows', 'super', 'self', 'throw', 'throws', 'true', 'try']);
const KOTLIN_KW = new Set(['as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if', 'in', 'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this', 'throw', 'true', 'try', 'typealias', 'typeof', 'val', 'var', 'when', 'while']);
const RESERVED_PROPS = new Set(['name', 'properties']);
function propIdent(p, kw) {
  let id = camel(p);
  if (/^\d/.test(id)) id = `_${id}`;
  if (RESERVED_PROPS.has(id)) id = `${id}Value`;
  return kw.has(id) ? `\`${id}\`` : id;
}
function props(e) {
  return Object.entries(e.properties ?? {}).map(([name, p]) => ({ name, ...p, required: p.required !== false }));
}
function enumCase(v) { let c = camel(String(v)); if (/^\d/.test(c)) c = `_${c}`; return c; }

function genSwiftAnalytics(list) {
  const swiftType = (e, p) => (p.enum ? `${pascal(e.name)}${pascal(p.name)}` : { string: 'String', integer: 'Int', number: 'Double', boolean: 'Bool' }[p.type ?? 'string'] ?? 'String');
  const valueCase = (p) => (p.enum ? 'string' : { integer: 'int', number: 'double', boolean: 'bool' }[p.type] ?? 'string');
  const L = [`// ${GEN}`, `// Source: contracts/analytics/events.json`, '', 'public enum AnalyticsValue: Sendable, Equatable {', '    case string(String)', '    case int(Int)', '    case double(Double)', '    case bool(Bool)', '}', ''];
  L.push('public enum AnalyticsEvent: Sendable, Equatable {');
  for (const e of list) {
    const ps = props(e);
    L.push(`    /// ${e.description ?? e.name}${e.feature ? ` (${e.feature})` : ''}`);
    L.push(`    case ${camel(e.name)}${ps.length ? `(${ps.map((p) => `${propIdent(p.name, SWIFT_KW).replace(/`/g, '')}: ${swiftType(e, p)}${p.required ? '' : '? = nil'}`).join(', ')})` : ''}`);
  }
  L.push('', '    public var name: String {', '        switch self {');
  for (const e of list) L.push(`        case .${camel(e.name)}: return "${e.name}"`);
  L.push('        }', '    }', '', '    public var properties: [String: AnalyticsValue] {', '        switch self {');
  for (const e of list) {
    const ps = props(e);
    if (!ps.length) { L.push(`        case .${camel(e.name)}: return [:]`); continue; }
    const binds = ps.map((p) => `let ${propIdent(p.name, SWIFT_KW)}`).join(', ');
    L.push(`        case .${camel(e.name)}(${binds}):`, '            var p: [String: AnalyticsValue] = [:]');
    for (const p of ps) {
      const id = propIdent(p.name, SWIFT_KW);
      const expr = (v) => `.${valueCase(p)}(${v}${p.enum ? '.rawValue' : ''})`;
      L.push(p.required ? `            p["${p.name}"] = ${expr(id)}` : `            if let ${id} { p["${p.name}"] = ${expr(id)} }`);
    }
    L.push('            return p');
  }
  L.push('        }', '    }', '}');
  for (const e of list) for (const p of props(e).filter((x) => x.enum)) {
    L.push('', `public enum ${swiftType(e, p)}: String, Sendable, CaseIterable {`);
    for (const v of p.enum) L.push(`    case ${enumCase(v)} = "${v}"`);
    L.push('}');
  }
  return L.join('\n') + '\n';
}

function genKotlinAnalytics(list, pkg = 'com.example.analytics.generated') {
  const ktType = (e, p) => (p.enum ? `${pascal(e.name)}${pascal(p.name)}` : { string: 'String', integer: 'Long', number: 'Double', boolean: 'Boolean' }[p.type ?? 'string'] ?? 'String');
  const L = [`// ${GEN}`, `// Source: contracts/analytics/events.json`, `package ${pkg}`, '', 'sealed interface AnalyticsEvent {', '    val name: String', '    val properties: Map<String, Any>'];
  for (const e of list) {
    const ps = props(e);
    L.push('', `    /** ${e.description ?? e.name}${e.feature ? ` (${e.feature})` : ''} */`);
    if (!ps.length) {
      L.push(`    data object ${pascal(e.name)} : AnalyticsEvent {`, `        override val name = "${e.name}"`, `        override val properties: Map<String, Any> = emptyMap()`, '    }');
      continue;
    }
    L.push(`    data class ${pascal(e.name)}(`);
    for (const p of ps) L.push(`        val ${propIdent(p.name, KOTLIN_KW)}: ${ktType(e, p)}${p.required ? '' : '? = null'},`);
    L.push('    ) : AnalyticsEvent {', `        override val name = "${e.name}"`, '        override val properties: Map<String, Any>', '            get() = buildMap {');
    for (const p of ps) {
      const id = propIdent(p.name, KOTLIN_KW);
      const v = p.enum ? `${p.required ? id : 'it'}.value` : p.required ? id : 'it';
      L.push(p.required ? `                put("${p.name}", ${v})` : `                ${id}?.let { put("${p.name}", ${v}) }`);
    }
    L.push('            }', '    }');
  }
  L.push('}');
  for (const e of list) for (const p of props(e).filter((x) => x.enum)) {
    L.push('', `enum class ${ktType(e, p)}(val value: String) {`);
    L.push(p.enum.map((v) => `    ${enumCase(v).replace(/[a-z0-9][A-Z]/g, (m) => `${m[0]}_${m[1]}`).toUpperCase()}("${v}")`).join(',\n') + ',');
    L.push('}');
  }
  return L.join('\n') + '\n';
}

function main() {
  const stringsSource = loadStrings();
  const events = loadEvents();

  for (const platform of ['ios', 'android']) {
    if (args.platform && args.platform !== platform) continue;
    const pc = config[platform];
    if (!pc) continue;
    const repo = path.resolve(root, pc.root ?? platform);
    if (!fs.existsSync(repo)) {
      if (args.check && !args['allow-missing']) missingRepos.push(path.relative(root, repo));
      else warnings.push(`${platform}: repo ${path.relative(root, repo)} not found, skipped`);
      continue;
    }
    repos.push(repo);
    if (want('copy')) for (const c of pc.copy ?? []) planCopy(path.resolve(root, c.from), path.resolve(repo, c.to));
    if (want('strings') && stringsSource && pc.strings) {
      if (platform === 'ios') {
        outputs.set(path.resolve(repo, pc.strings.to), genXcstrings(stringsSource));
        if (pc.strings.accessors) outputs.set(path.resolve(repo, pc.strings.accessors), genSwiftAccessors(stringsSource, pc.strings.bundle ?? 'Bundle.module'));
        if (pc.strings.infoPlist) outputs.set(path.resolve(repo, pc.strings.infoPlist.to), genInfoPlistStrings(stringsSource, pc.strings.infoPlist.keys ?? {}));
      }
      else for (const [dir, xml] of genAndroidStrings(stringsSource)) outputs.set(path.resolve(repo, pc.strings.resDir, dir, pc.strings.fileName ?? 'strings.xml'), xml);
    }
    if (want('analytics') && events && pc.analytics) {
      outputs.set(path.resolve(repo, pc.analytics.to), platform === 'ios' ? genSwiftAnalytics(events) : genKotlinAnalytics(events, pc.analytics.package));
    }
  }

  // ---- manifests: what each repo should contain after this run ----
  for (const repo of repos) {
    const mine = [...outputs.keys()].filter((f) => f.startsWith(repo + path.sep)).map((f) => path.relative(repo, f).split(path.sep).join('/')).sort();
    const manifestPath = path.join(repo, MANIFEST);
    const previous = fs.existsSync(manifestPath) ? JSON.parse(fs.readFileSync(manifestPath, 'utf8')).files ?? [] : [];
    for (const old of previous.filter((f) => !mine.includes(f))) {
      const abs = path.join(repo, old);
      if (!fs.existsSync(abs)) continue;
      if (args.check) { stale++; console.log(`✖ extra   ${path.relative(root, abs)} (no longer generated)`); }
      else { fs.rmSync(abs); console.log(`✔ removed ${path.relative(root, abs)}`); }
    }
    outputs.set(manifestPath, JSON.stringify({ note: GEN, files: mine }, null, 2) + '\n');
  }

  // ---- apply or check ----
  for (const r of missingRepos) { stale++; console.log(`✖ missing repo ${r} (clone it, or pass --allow-missing)`); }
  for (const [file, content] of outputs) {
    const rel = path.relative(root, file);
    const current = fs.existsSync(file) ? fs.readFileSync(file) : null;
    const same = current !== null && (file.endsWith('.xcstrings') ? sameJson(current, content) : Buffer.compare(current, Buffer.from(content)) === 0);
    if (args.check) { if (!same) { stale++; console.log(`✖ ${current === null ? 'missing' : 'stale  '} ${rel}`); } continue; }
    if (same) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`✔ wrote ${rel}`);
  }
  for (const w of warnings) console.warn(`! ${w}`);
  if (args.check) {
    if (stale) { console.error(`✖ ${stale} file(s) out of sync — run: node tools/contracts-sync.mjs`); process.exit(1); }
    console.log(`✔ ${outputs.size} generated/copied file(s) in sync`);
  } else console.log(`done: ${outputs.size} file(s) checked`);
}

main();
