#!/usr/bin/env node
/**
 * deps-report.mjs — one view of every third-party dependency in the workspace, both platforms side by side.
 *
 * Usage:
 *   node tools/deps-report.mjs [--ios ios] [--android android] [--out parity/DEPENDENCIES.md]
 *
 * Reads (offline, no network):
 *   iOS      every Package.resolved (SPM pins, formats v1–v3) and project.pbxproj (deployment target, Swift version),
 *            .xcode-version if present
 *   Android  gradle/libs.versions.toml (versions, libraries, plugins), gradle-wrapper.properties,
 *            compileSdk / targetSdk / minSdk found in build scripts
 *   Agents   skills/lock.json (pins and their age)
 * Pairs vendor SDKs that must stay on the same generation on both platforms (analytics, crash, flags, push, payments…).
 * It doesn't check for newer versions. Use Renovate/Dependabot and `skills-sync --outdated` for that (HOW_TO_UPDATE.md).
 */
import fs from 'node:fs';
import path from 'node:path';
import { WORKSPACE, parseArgs, printHelp, walk, toPosix, mdTable, today } from './lib/common.mjs';

const args = parseArgs(process.argv.slice(2), ['help']);
if (args.help) { printHelp(import.meta.url); process.exit(0); }
const root = path.resolve(args.workspace ?? WORKSPACE);
const iosDir = path.resolve(root, args.ios ?? 'ios');
const androidDir = path.resolve(root, args.android ?? 'android');
const rel = (p) => toPosix(path.relative(root, p));

// Vendor families whose SDKs must move together on both platforms (keyword → matched in package identity / Maven coordinates).
const VENDORS = {
  Firebase: ['firebase'], Sentry: ['sentry'], Amplitude: ['amplitude'], Mixpanel: ['mixpanel'], Segment: ['segment', 'analytics-swift', 'analytics-kotlin'],
  PostHog: ['posthog'], Braze: ['braze'], OneSignal: ['onesignal'], RevenueCat: ['revenuecat', 'purchases'], Stripe: ['stripe'],
  LaunchDarkly: ['launchdarkly'], Statsig: ['statsig'], Lottie: ['lottie'], Facebook: ['facebook'], 'Google Sign-In': ['googlesignin', 'google-signin', 'play-services-auth'],
  AppAuth: ['appauth'], Mapbox: ['mapbox'], 'Google Maps': ['googlemaps', 'maps-compose', 'play-services-maps'], Apollo: ['apollo'], Bugsnag: ['bugsnag'],
};

const ios = readIos();
const android = readAndroid();
const skills = readSkills();

let md = `# Third-party dependencies\n\n> Generated by \`tools/deps-report.mjs\` on ${new Date().toISOString()}. **Do not edit.** How to update: \`HOW_TO_UPDATE.md\`.\n\n`;
md += `## Toolchains\n\n`;
md += mdTable(['Platform', 'Item', 'Value', 'Source'], [
  ...ios.toolchain.map((t) => ['iOS', t[0], t[1], t[2]]),
  ...android.toolchain.map((t) => ['Android', t[0], t[1], t[2]]),
]);
md += `\n## Vendor SDKs that must stay aligned across platforms\n\n`;
const vendorRows = Object.entries(VENDORS).map(([vendor, keys]) => {
  const hit = (s) => keys.some((k) => s.toLowerCase().includes(k));
  const i = ios.pins.filter((p) => hit(`${p.name} ${p.location}`));
  const a = android.libraries.filter((l) => hit(`${l.alias} ${l.module}`));
  if (!i.length && !a.length) return null;
  const fmt = (list, f) => list.map(f).join('<br>') || '**missing**';
  return [vendor, fmt(i, (p) => `${p.name} ${p.version ?? p.revision?.slice(0, 7) ?? '?'}`), fmt(a, (l) => `${l.module} ${l.version ?? 'BOM'}`)];
}).filter(Boolean);
md += vendorRows.length ? mdTable(['Vendor', 'iOS', 'Android'], vendorRows) : '_none detected_\n';
md += `\n"**missing**" on one side means one platform uses the vendor and the other doesn't. Check that's intentional (divergence register).\n`;
md += `\n## iOS: Swift Package Manager pins (${ios.pins.length})\n\n`;
md += mdTable(['Package', 'Version / revision', 'Location', 'Resolved in'], ios.pins.map((p) => [p.name, p.version ?? (p.branch ? `branch ${p.branch} @ ${p.revision?.slice(0, 7)}` : p.revision?.slice(0, 7)), p.location, p.file]));
if (ios.pins.some((p) => !p.version)) md += `\n⚠︎ Pins without a version (branch or revision) can't be tracked by update bots. Pin a release.\n`;
md += `\n## Android: version catalog (${android.libraries.length} libraries, ${android.plugins.length} plugins)\n\n`;
md += mdTable(['Alias', 'Module / plugin', 'Version', 'Kind'], [
  ...android.libraries.map((l) => [l.alias, l.module, l.version ?? '(BOM-managed)', 'library']),
  ...android.plugins.map((p) => [p.alias, p.id, p.version ?? '?', 'plugin']),
]);
md += `\n## Agent skills (skills/lock.json)\n\n`;
md += mdTable(['Source', 'Ref', 'Commit', 'Pinned on', 'Age (days)', 'Skills'], skills.map((s) => [s.id, s.ref ?? '', s.commit.slice(0, 7), s.pinnedOn ?? '?', s.age ?? '?', s.skills]));
md += `\nRun \`node tools/skills-sync.mjs --outdated\` to compare with upstream.\n`;

if (args.out) { const out = path.resolve(root, args.out); fs.mkdirSync(path.dirname(out), { recursive: true }); fs.writeFileSync(out, md); console.log(`✔ wrote ${rel(out)}`); }
else process.stdout.write(md);

// ---------- readers ----------
function readIos() {
  const out = { pins: [], toolchain: [] };
  if (!fs.existsSync(iosDir)) { out.toolchain.push(['repo', 'not found', rel(iosDir)]); return out; }
  const seen = new Map();
  for (const f of walk(iosDir)) {
    const base = path.basename(f);
    if (base === 'Package.resolved') {
      let j; try { j = JSON.parse(fs.readFileSync(f, 'utf8')); } catch { continue; }
      const pins = j.pins ?? j.object?.pins ?? [];
      for (const p of pins) {
        const name = p.identity ?? p.package;
        const pin = { name, location: p.location ?? p.repositoryURL ?? '', version: p.state?.version ?? null, branch: p.state?.branch ?? null, revision: p.state?.revision ?? null, file: rel(f) };
        const prev = seen.get(name);
        if (prev && prev.version !== pin.version) out.toolchain.push(['⚠︎ conflicting pins', `${name}: ${prev.version} vs ${pin.version}`, `${prev.file} / ${pin.file}`]);
        if (!prev) { seen.set(name, pin); out.pins.push(pin); }
      }
    } else if (base === 'project.pbxproj') {
      const t = fs.readFileSync(f, 'utf8');
      const uniq = (re) => [...new Set([...t.matchAll(re)].map((m) => m[1]))].join(', ');
      const dt = uniq(/IPHONEOS_DEPLOYMENT_TARGET = ([\d.]+);/g);
      const sv = uniq(/SWIFT_VERSION = ([\d.]+);/g);
      if (dt) out.toolchain.push(['iOS deployment target', dt, rel(f)]);
      if (sv) out.toolchain.push(['Swift language version', sv, rel(f)]);
    } else if (base === '.xcode-version') {
      out.toolchain.push(['Xcode', fs.readFileSync(f, 'utf8').trim(), rel(f)]);
    } else if (base === 'Package.swift') {
      const tools = fs.readFileSync(f, 'utf8').match(/swift-tools-version:\s*([\d.]+)/)?.[1];
      if (tools) out.toolchain.push(['swift-tools-version', tools, rel(f)]);
    }
  }
  out.pins.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

function readAndroid() {
  const out = { libraries: [], plugins: [], toolchain: [] };
  if (!fs.existsSync(androidDir)) { out.toolchain.push(['repo', 'not found', rel(androidDir)]); return out; }
  const catalog = path.join(androidDir, 'gradle', 'libs.versions.toml');
  if (fs.existsSync(catalog)) {
    const toml = parseToml(fs.readFileSync(catalog, 'utf8'));
    const versions = toml.versions ?? {};
    const ver = (v) => (v == null ? null : typeof v === 'string' ? v : v['version.ref'] ? versions[v['version.ref']] ?? `ref ${v['version.ref']}?` : v.version ?? null);
    for (const [alias, v] of Object.entries(toml.libraries ?? {})) {
      const module = typeof v === 'string' ? v.split(':').slice(0, 2).join(':') : v.module ?? `${v.group}:${v.name}`;
      const version = typeof v === 'string' ? v.split(':')[2] ?? null : ver(v);
      out.libraries.push({ alias, module, version });
    }
    for (const [alias, v] of Object.entries(toml.plugins ?? {})) {
      out.plugins.push({ alias, id: typeof v === 'string' ? v.split(':')[0] : v.id, version: typeof v === 'string' ? v.split(':')[1] : ver(v) });
    }
    for (const key of ['agp', 'androidGradlePlugin', 'kotlin', 'composeBom', 'compose-bom', 'ksp', 'hilt']) if (versions[key]) out.toolchain.push([key, versions[key], rel(catalog)]);
  } else out.toolchain.push(['version catalog', 'not found', rel(catalog)]);
  const wrapper = path.join(androidDir, 'gradle', 'wrapper', 'gradle-wrapper.properties');
  if (fs.existsSync(wrapper)) {
    const v = fs.readFileSync(wrapper, 'utf8').match(/gradle-([\d.]+(?:-rc-\d+)?)-(?:bin|all)\.zip/)?.[1];
    if (v) out.toolchain.push(['Gradle wrapper', v, rel(wrapper)]);
  }
  const sdk = { compileSdk: new Set(), targetSdk: new Set(), minSdk: new Set() };
  for (const f of walk(androidDir)) {
    if (!/\.(gradle|gradle\.kts|kt)$/.test(f) || !/(build-logic|build\.gradle)/.test(toPosix(f))) continue;
    const t = fs.readFileSync(f, 'utf8');
    for (const k of Object.keys(sdk)) for (const m of t.matchAll(new RegExp(`${k}(?:Version)?\\s*=?\\s*(\\d+)`, 'g'))) sdk[k].add(m[1]);
  }
  for (const [k, set] of Object.entries(sdk)) if (set.size) out.toolchain.push([k, [...set].join(', '), 'build scripts']);
  out.libraries.sort((a, b) => a.module.localeCompare(b.module));
  return out;
}

function readSkills() {
  const lockPath = path.join(root, 'skills', 'lock.json');
  if (!fs.existsSync(lockPath)) return [];
  const lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'));
  const now = new Date(today());
  return lock.sources.map((s) => ({
    ...s,
    age: s.pinnedOn ? Math.round((now - new Date(s.pinnedOn)) / 86400000) : null,
    skills: s.skills.filter((k) => k.enabled !== false).map((k) => k.installAs).join(', '),
  }));
}

/** Minimal TOML reader for Gradle version catalogs: [section], key = "string" | { inline table }. */
function parseToml(text) {
  const out = {};
  let section = null;
  for (const raw of text.split('\n')) {
    const line = raw.replace(/\s+#.*$/, '').trim();
    if (!line || line.startsWith('#')) continue;
    const sec = line.match(/^\[([^\]]+)\]$/);
    if (sec) { section = sec[1]; out[section] ??= {}; continue; }
    const kv = line.match(/^([\w.\-"]+)\s*=\s*(.+)$/);
    if (!kv || !section) continue;
    const key = kv[1].replace(/"/g, '');
    const val = kv[2].trim();
    if (val.startsWith('"')) out[section][key] = val.replace(/^"|"$/g, '');
    else if (val.startsWith('{')) {
      const obj = {};
      for (const m of val.slice(1, -1).matchAll(/([\w.]+)\s*=\s*"([^"]*)"/g)) obj[m[1]] = m[2];
      for (const m of val.slice(1, -1).matchAll(/version\s*=\s*\{\s*strictly\s*=\s*"([^"]*)"/g)) obj.version = m[1];
      out[section][key] = obj;
    }
  }
  return out;
}
